name: Deploy to Hugging Face spaces

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}

        run: |
          git remote add hf https://thiagohersan:$HFTOKEN@huggingface.co/spaces/5020A/5020-ColorSort-Gradio
          git push -f hf main
